version: '3'


services:
  rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
  client:
    image: dofe71/soa_chat:latest
    command: ./bin/spammer
    environment:
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
        - rabbitmq


  